// src/screens/app/LessonPlanScreen.tsx
import React from "react";
import { View, Text, StyleSheet } from "react-native";
import { useAuth } from "../../context/AuthContext";

const LessonPlanScreen: React.FC = () => {
  const { user } = useAuth();

  return (
    <View style={styles.container}>
      <Text style={styles.title}>Today’s lesson plan</Text>
      <Text style={styles.subtitle}>
        Based on your current level: {user?.level}
      </Text>

      <View style={styles.card}>
        <Text style={styles.cardTitle}>1. Warm-up speaking (5 min)</Text>
        <Text style={styles.cardText}>
          Answer 3 simple questions about your day in the target language.
        </Text>
      </View>

      <View style={styles.card}>
        <Text style={styles.cardTitle}>2. Listening mini-task (10 min)</Text>
        <Text style={styles.cardText}>
          Short audio about everyday life. Focus on catching key verbs and time
          expressions.
        </Text>
      </View>

      <View style={styles.card}>
        <Text style={styles.cardTitle}>3. Feedback & corrections</Text>
        <Text style={styles.cardText}>
          The AI tutor highlights mistakes and offers native-like alternatives.
        </Text>
      </View>

      <Text style={styles.note}>
        (Later we’ll make this fully dynamic and generated by the AI.)
      </Text>
    </View>
  );
};

const styles = StyleSheet.create({
  container: { flex: 1, padding: 24, backgroundColor: "#020617" },
  title: { fontSize: 22, fontWeight: "700", color: "#fff", marginBottom: 4 },
  subtitle: { fontSize: 14, color: "#9ca3af", marginBottom: 16 },
  card: {
    backgroundColor: "#0b1120",
    padding: 16,
    borderRadius: 16,
    marginBottom: 12,
  },
  cardTitle: { color: "#e5e7eb", fontWeight: "600", marginBottom: 4 },
  cardText: { color: "#9ca3af", fontSize: 13 },
  note: { marginTop: 16, color: "#6b7280", fontSize: 12 },
});

export default LessonPlanScreen;
